version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db_users
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - ":3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  data-generator:
    build: 
      context: ../data-generator
      dockerfile: Dockerfile.mysql
    environment:
      - DATABASE_URL=mysql+mysqlconnector://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
